/-
  Browser entry point for Tour 00: the app generated by the `component Hello`
  declaration, mounted as the whole program. Transpiled to JavaScript by `qed build`
  (`QED_WEB_ROOT=Examples.HelloWeb`).
-/
import Examples.Hello
import Qed.Driver

def main : IO Unit := Qed.run Hello.app
